services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    expose:
      - 8000
  
    env_file:
      - .env.prod
    restart: always
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env.prod
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 15s
      timeout: 5s
      retries: 5
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  db_data:
  static_volume: