# Generated by Django 5.1.6 on 2025-02-09 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='board',
            name='uid',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('user', 'uid')},
        ),
    ]
