# Generated by Django 5.1.6 on 2025-02-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_moisuresensor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoisureSensor',
            new_name='MoistureSensor',
        ),
    ]
