# Generated by Django 5.1.6 on 2025-02-12 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_reading_options_alter_board_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoisureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sensor_slot', models.CharField(choices=[('A', 'Sensor A'), ('B', 'Sensor B'), ('C', 'Sensor C')], max_length=1)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='api.board')),
            ],
        ),
    ]
